apiVersion: apps/v1
kind: Deployment
metadata:
  name: env-demo
  labels: { app: env-demo }
spec:
  replicas: 2
  selector:
    matchLabels: { app: env-demo }
  template:
    metadata:
      labels: { app: env-demo }
    spec:
      containers:
        - name: myapp
          image: busybox
          command: ["sh", "-c", "echo DB_USER=$DB_USER && echo DB_PASS=$DB_PASS && sleep 3600"]
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password