apiVersion: v1
kind: Pod
metadata:
  name: metadata-file-demo
  annotations:
    build.version: "1.0.3"
spec:
  containers:
    - name: app
      image: busybox
      command: ["sh", "-c", "cat /etc/podinfo/annotations; sleep 3600"]
      volumeMounts:
        - name: podinfo
          mountPath: /etc/podinfo
  volumes:
    - name: podinfo
      downwardAPI: # Downward API Volume to expose Pod metadata
        items:
          - path: "annotations"
            fieldRef:
              fieldPath: metadata.annotations