apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-green
  labels:
    app: demo-app
    version: green
  annotations:
    kubernetes.io/change-cause: "Green: nginx 1.27.1-alpine"
spec:
  replicas: 3
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: demo-app
      version: green
  template:
    metadata:
      labels:
        app: demo-app
        version: green
    spec:
      containers:
        - name: app
          image: nginx:1.27.1-alpine  # <— new version here
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet: { path: "/", port: 80 }
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: "/", port: 80 }
            initialDelaySeconds: 10
            periodSeconds: 10