apiVersion: v1
kind: Service
metadata:
  name: demo-app
  labels:
    app: demo-app
spec:
  type: ClusterIP
  selector:
    app: demo-app
    version: blue          # <— flip to "green" to switch traffic
  ports:
    - name: http
      port: 80
      targetPort: 80