apiVersion: v1
kind: Pod
metadata:
  name: shared-volume-pod
spec:
  containers:
    - name: writer
      image: busybox
      command: ["sh", "-c", "echo Hello from writer! > /data/hello.txt && sleep 3600"]
      volumeMounts:
        - name: shared-volume
          mountPath: /data
    - name: reader
      image: busybox
      command: ["sh", "-c", "cat /data/hello.txt && sleep 3600"]
      volumeMounts:
        - name: shared-volume
          mountPath: /data
  volumes:
    - name: shared-volume
      emptyDir: {}