apiVersion: v1
kind: ConfigMap
metadata:
  name: app-cfg
data:
  APP_MODE: production
  APP_COLOR: blue
---
apiVersion: v1
kind: Pod
metadata:
  name: cm-one-key-env
spec:
  containers:
    - name: app
      image: busybox
      command: ["sh","-c","echo mode=$MODE; sleep 3600"]
      env:
        - name: MODE
          valueFrom:
            configMapKeyRef:
              name: app-cfg
              key: APP_MODE
