apiVersion: v1
kind: Pod
metadata:
  name: env-demo
spec:
  containers:
    - name: web
      image: nginx
      env:
        - name: APP_ENV
          value: "production"
        - name: LOG_LEVEL
          value: "debug"
        - name: MAX_CONNECTIONS
          value: "100"