apiVersion: v1
kind: Pod
metadata:
  name: pod-hostpath-test
spec:
  containers:
    - name: app
      image: busybox
      command: ["sh", "-c", "echo hello > /data/hello.txt && sleep 3600"]
      volumeMounts:
        - name: vol
          mountPath: /data
  volumes:
    - name: vol
      persistentVolumeClaim:
        claimName: pvc-hostpath-1

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: my-local-sc
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hostpath-1
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: my-local-sc
  hostPath:
    path: /mnt/data/pv1

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-hostpath-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: my-local-sc
