apiVersion: v1
kind: Pod
metadata:
  name: busybox-logger
spec:
  containers:
  - name: busybox-1
    image: busybox
    command:
      - "sh"
      - "-c"
      - "while true; do echo Hello from BusyBox 1; sleep 1; done"
    resources:
      requests:
        cpu: "100m"
        memory: "64Mi"
      limits:
        cpu: "100"
        memory: "64Mi"
  restartPolicy: Always