apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    command:
      - "sleep"
      - "1000"
    resources:
      requests:
        cpu: "100m"
        memory: "64Mi"
      limits:
        cpu: "100"
        memory: "64Mi"