apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  app.conf: |
    MODE=production
    PORT=8080
---
apiVersion: v1
kind: Pod
metadata:
  name: configmap-volume-pod
spec:
  containers:
    - name: app
      image: busybox
      command: ["sh", "-c", "cat /etc/config/app.conf; sleep 3600"]
      volumeMounts:
        - name: config-volume
          mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: app-config
