apiVersion: v1
kind: Pod
metadata:
  name: pod-test
spec:
  containers:
    - name: app
      image: busybox
      command: ["sh", "-c", "echo Hello from PVC > /data/hello.txt && sleep 3600"]
      volumeMounts:
        - mountPath: /data
          name: test-volume
  volumes:
    - name: test-volume
      persistentVolumeClaim:
        claimName: pvc-test
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
